filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/src/logstash/my-app.log
    fields:
      log_type: nestjs

  - type: log
    enabled: true
    paths:
      - /usr/src/logstash/transaction-audit.log
    fields:
      log_type: transaction

  - type: log
    enabled: true
    paths:
      - /usr/src/logstash/transaction-reversal-audit.log
    fields:
      log_type: transaction-reversal

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"